// Enhanced mock data with more detailed analytics
export const mockData = {
  totalUsers: 2847,
  activeUsers: 1923,
  newUsersToday: 47,
  totalBookings: 8934,
  bookingsToday: 234,
  revenue: 127890,
  revenueGrowth: 18.7,
  userGrowth: 12.4,
  bookingGrowth: 23.1,
  conversionRate: 4.2,
  avgSessionDuration: "12m 34s",
  peakHours: "6-8 PM",
  membershipRetention: 89.3,
  recentBookings: [
    {
      id: 1,
      user: "Emma Thompson",
      service: "Personal Training",
      date: "Today, 10:30 AM",
      status: "confirmed",
      amount: 120,
    },
    {
      id: 2,
      user: "Michael Chen",
      service: "Yoga Class",
      date: "Today, 2:00 PM",
      status: "confirmed",
      amount: 35,
    },
    {
      id: 3,
      user: "Sarah Johnson",
      service: "Group HIIT",
      date: "Today, 5:30 PM",
      status: "pending",
      amount: 45,
    },
    {
      id: 4,
      user: "David Wilson",
      service: "Swimming Session",
      date: "Tomorrow, 8:00 AM",
      status: "confirmed",
      amount: 60,
    },
    {
      id: 5,
      user: "Olivia Martinez",
      service: "Spin Class",
      date: "Tomorrow, 7:00 PM",
      status: "cancelled",
      amount: 40,
    },
    {
      id: 6,
      user: "James Rodriguez",
      service: "CrossFit",
      date: "Tomorrow, 9:00 AM",
      status: "confirmed",
      amount: 80,
    },
  ],
  topServices: [
    {
      name: "Personal Training",
      bookings: 342,
      growth: 18,
      revenue: 41040,
      color: "#3B82F6",
    },
    {
      name: "Yoga Classes",
      bookings: 289,
      growth: 12,
      revenue: 10115,
      color: "#10B981",
    },
    {
      name: "Group HIIT",
      bookings: 234,
      growth: 25,
      revenue: 10530,
      color: "#F59E0B",
    },
    {
      name: "Spin Classes",
      bookings: 198,
      growth: 8,
      revenue: 7920,
      color: "#EF4444",
    },
    {
      name: "Swimming Sessions",
      bookings: 156,
      growth: -3,
      revenue: 9360,
      color: "#8B5CF6",
    },
    {
      name: "CrossFit",
      bookings: 134,
      growth: 31,
      revenue: 10720,
      color: "#06B6D4",
    },
  ],
  usersByMembership: [
    { type: "Premium", count: 1124, color: "#FFD700", percentage: 39.5 },
    { type: "Standard", count: 1289, color: "#3B82F6", percentage: 45.3 },
    { type: "Basic", count: 434, color: "#10B981", percentage: 15.2 },
  ],
  revenueByMonth: [
    { month: "Jan", revenue: 98500, bookings: 1240 },
    { month: "Feb", revenue: 105200, bookings: 1356 },
    { month: "Mar", revenue: 112800, bookings: 1445 },
    { month: "Apr", revenue: 118900, bookings: 1523 },
    { month: "May", revenue: 124300, bookings: 1612 },
    { month: "Jun", revenue: 127890, bookings: 1689 },
  ],
  hourlyBookings: [
    { hour: "6 AM", bookings: 45 },
    { hour: "7 AM", bookings: 78 },
    { hour: "8 AM", bookings: 92 },
    { hour: "9 AM", bookings: 67 },
    { hour: "10 AM", bookings: 54 },
    { hour: "11 AM", bookings: 43 },
    { hour: "12 PM", bookings: 38 },
    { hour: "1 PM", bookings: 41 },
    { hour: "2 PM", bookings: 52 },
    { hour: "3 PM", bookings: 63 },
    { hour: "4 PM", bookings: 71 },
    { hour: "5 PM", bookings: 89 },
    { hour: "6 PM", bookings: 124 },
    { hour: "7 PM", bookings: 142 },
    { hour: "8 PM", bookings: 118 },
    { hour: "9 PM", bookings: 87 },
  ],
};
